### PR TITLE
Add types and printf in TooManyRequestsException

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://twitter.com/danjharrin/status/1351151639533678594
By `phpstan analyze src/ -l max`

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danharrin Friendly ping.

**Comment by danharrin** [comment]
Hey, I'm not interested in typing those properties. Could you please remove those lines and I will merge. Many thanks!

**Comment by szepeviktor** [comment]
> Could you please remove those lines

The wish of the century!

Done 🍏

**Comment by danharrin** [comment]
Thank you Viktor :)

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
