### PR TITLE
Laravel 10

### PR DESCRIPTION
**Pull request by RohanSakhale**

### CODE REVIEW

**Comment by RohanSakhale** [comment]
@danharrin can you just give a check at this PR

**Comment by danharrin** [comment]
We already added L10 support so not sure why we need to bump these deps 🤔

**Comment by danharrin** [comment]
Also composer.lock should always be committed...

**Comment by danharrin** [comment]
No, that's wrong. composer.lock is not used when users install the package, only when maintainers install.

**Comment by RohanSakhale** [comment]
> No, that's wrong. composer.lock is not used when users install the package, only when maintainers install.

I see, that's helpful, thanks for the correction

**Pull request merged**
